### ISSUE TITLE
extern "C" { prototype_tilde_setup(); } needed in .mm files for the externals

### ISSUE THREAD

**Issue by mikegao4005** [libpd/pd-for-ios#10]
if using external in objective C,
extern prototype_tilde_setup();
will not work
will need extern "C" { prototype_tilde_setup(); } for externals ...

Maybe good to put this in the help page because I got stuck on it for a while.

**Comment by danomatika** [comment]
This info was added to the libpd wiki: https://github.com/libpd/libpd/wiki/Adding-Pure-Data-external-libraries-to-your-project
