### ISSUE TITLE
abl_link: use variables for paths to 3rd-party modules

### ISSUE THREAD

**Issue by umlaeute** [libpd/pd-for-ios#12]
please use variables for the paths to 3rd-party modules, e.g.

```
     LINK_INCLUDE=./link/include
     ASIO_INCLUDE=./link/modules/asio-standalone/asio/include

     cflags = -std=c++11 -I$(LINK_INCLUDE) -I$(ASIO_INCLUDE) -Wno-multichar
```

**Comment by umlaeute** [comment]
this is mainly needed when using a "central" installation of ableton-link and asio (e.g. on Debian) and downloading the zip-file of "abl_link" (either from the repo, or via deken), which lacks any git submodules.

**Comment by nettoyeurny** [comment]
This seems simpler:

LINK_HOME ?= ./link
cflags = ... -I$(LINK_HOME)/include -I$(LINK_HOME)/modules/asio-standalone/asio/include ...

I made this change and pushed it to the new repo: https://github.com/libpd/abl_link

I'll close this issue now. Please open a new issue against the new repo is this solution doesn't work for you.
