### ISSUE TITLE
PdLinkSample Xcode compilation issues

### ISSUE THREAD

**Issue by Audionomy** [libpd/pd-for-ios#15]
Hi,
I haven't been able to build and run the PdLinkSample project in XCode. I keep getting "undefined symbols" compilation errors (see below). I have carefully checked my library and header search paths. I have tried various C++ compiler options in XCode. No luck so far. Has anyone had the same issues? Sounds like I am missing a particular setting somewhere, but which one?
Pascal
```
Undefined symbols for architecture arm64:
  "_ABLLinkCaptureAudioTimeline", referenced from:
      _abl_link_tilde_tick in abl_link.o
      _abl_link_tilde_tick in PdLinkAudioUnit.o
  "_ABLLinkSetTempo", referenced from:
      _abl_link_tilde_tick in abl_link.o
      _abl_link_tilde_tick in PdLinkAudioUnit.o
  "_ABLLinkCommitAudioTimeline", referenced from:
      _abl_link_tilde_tick in abl_link.o
      _abl_link_tilde_tick in PdLinkAudioUnit.o
  "_ABLLinkCaptureAppTimeline", referenced from:
      -[ViewController viewDidLoad] in ViewController.o
  "_ABLLinkRequestBeatAtTime", referenced from:
      _abl_link_tilde_tick in abl_link.o
      _abl_link_tilde_tick in PdLinkAudioUnit.o
  "_ABLLinkBeatAtTime", referenced from:
      _abl_link_tilde_tick in abl_link.o
      _abl_link_tilde_tick in PdLinkAudioUnit.o
  "_ABLLinkGetTempo", referenced from:
      -[ViewController viewDidLoad] in ViewController.o
      _abl_link_tilde_tick in abl_link.o
      _abl_link_tilde_tick in PdLinkAudioUnit.o
```

**Comment by ragnaringi** [comment]
@Audionomy You need to request access to the LinkKit SDK for iOS http://ableton.github.io/linkkit/ and then include in PdLinkSample

**Comment by Audionomy** [comment]
ok thanks

**Comment by headkit** [comment]
does not work anymore. I get the errors

> "Implicit declaration of function 'ABLLinkCaptureAppTimeline' is invalid in C99"

and

> ".....pd-for-ios/pd-for-ios/PdLinkSample/PdLinkSample/ViewController.m:41:5: Use of undeclared identifier 'ABLLinkTimelineRef'; did you mean 'ABLLinkTimeAtBeat'?"

for the line 
`ABLLinkTimelineRef timeline = ABLLinkCaptureAppTimeline(linkRef);`
in ViewController.m
