### ISSUE TITLE
Errors (Invalid channel Configuration) when running Circle Of Fifths sample - opensl

### ISSUE THREAD

**Issue by ghost** [libpd/pd-for-ios#2]
I thought I would post these here instead of letting them pass unmentioned... I am running Circle Of Fifths and both the master branch and opensl branch give the follow errors at startup:

07-09 00:55:59.620: E/AudioTrack-Java(19859): [ android.media.AudioTrack ] getMinBufferSize(): Invalid channel configuration.
07-09 00:55:59.620: E/AudioTrack-Java(19859): [ android.media.AudioTrack ] getMinBufferSize(): Invalid channel configuration.

I am not familiar with this part of libpd, so I'm not sure what is failing, just thought you should know if you don't already..

**Comment by danomatika** [comment]
Closing due to age. Also, sounds like this is a problem with one of the pd-for-android examples, if it continues please open an issue on that repo.
