### ISSUE TITLE
Errors in Circle Of Fifths, opensl only: FimgApiStretch:stretch failed

### ISSUE THREAD

**Issue by ghost** [libpd/pd-for-ios#3]
A different error in Circle Of Fifths, this one only in the opensl branch.  When press on one of the keys in the circle, I get the error message:

07-09 00:56:17.725: E/SKIA(19859): FimgApiStretch:stretch failed

Everything else seems to be running fine.

Android version is 4.04

**Comment by danomatika** [comment]
Closing due to age. Also, sounds like this is a problem with one of the pd-for-android examples, if it continues please open an issue on that repo.
