### ISSUE TITLE
Can't run PdTest02 on iOS6

### ISSUE THREAD

**Issue by onato** [libpd/pd-for-ios#4]
After changing the Architectures build setting to ARCHS_STANDARD_32_BIT I could compile the PdTest02 demo for iOS6 but it does not produce any sound. It works fine on iOS5 and in the simulator. 

iPhone 4 iOS5 = Yes
iPhone Simulator iOS6 = Yes
iPhone 5 iOS6 = No
iPad 3 iOS6 = No

Any ideas why this is not working?

**Comment by danomatika** [comment]
Closing due to age. Reopen if the issue continues.
