### ISSUE TITLE
libpd folder is empty?

### ISSUE THREAD

**Issue by roecrew** [libpd/pd-for-ios#6]
So I downloaded pd-for-ios a few months ago, but accidently deleted the pdtest01 sample project.
So I re-downloaded it today, and I noticed that the libpd folder was empty.
This isn't a problem for me since I already have the files, but for a first time downloader...

**Comment by danomatika** [comment]
You can also cd into a submodule dir and then do a pull and/or checkout a newer tag.

In any case, the submodule has been updated more regularly now, so I'm closing the issue.
