### ISSUE TITLE
Compile error while working through the book's example

### ISSUE THREAD

**Issue by gregrberger** [libpd/pd-for-ios#8]
I have been following along with the book "Making Musical Apps," and I get an error when building: "Apple Mach-O Linker Error _OBJ_C_$_PdAudioController." I have a feeling that it has to do with the "User Header Search Path," I'm pretty confident that I have it correct. 

Any help would be greatly appreciated! I really want to get to know Pd...

**Comment by danomatika** [comment]
Closing due to age. Reopen if the issue continues.
